import Head from 'next/head';

// @ts-ignore
import { Button, Stack } from '@vimeo-ux/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack gap="2">
          <Button>Click me</Button>
          <Button>Click me again</Button>
        </Stack>
      </main>
    </>
  );
}
